apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: trainium
spec:
  template:
    metadata:
      labels:
        NodePool: trainium
    spec:
      taints:
        - key: aws.amazon.com/neuron
          value: "true"
          effect: "NoSchedule"
        - key: "NodePool"
          value: "trainium"
          effect: "NoSchedule"
      requirements:
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand"]
        - key: "node.kubernetes.io/instance-type"
          operator: In
          values: ["trn1.2xlarge"]
      nodeClassRef:
        name: basic
        group: eks.amazonaws.com
        kind: NodeClass
  limits:
    cpu: 1000
