apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: cpu-arm-graviton
spec:
  template:
    metadata:
      labels:
        NodePool: cpu-arm-graviton
    spec:
      requirements:
        - key: "kubernetes.io/arch"
          operator: In
          values: ["arm64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand"]
        - key: "node.kubernetes.io/instance-type"
          operator: In
          values: ["m7g.2xlarge"]
      nodeClassRef:
        name: basic
        group: eks.amazonaws.com
        kind: NodeClass
  limits:
    cpu: 1000
